# Generated by Django 6.0.3 on 2026-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('mfa_setup', 'MFA Setup'), ('forgot_password', 'Forgot Password')], max_length=20),
        ),
    ]
