# Generated by Django 6.0.3 on 2026-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='shop_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='shop_phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
