# Generated by Django 6.0.3 on 2026-04-05 09:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_is_superuser'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='document',
            name='encrypted_storage_ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='encryption_key_ref',
            field=models.CharField(default=datetime.datetime(2026, 4, 5, 9, 55, 37, 46160, tzinfo=datetime.timezone.utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('oauth_login', 'OAuth Login'), ('oauth_connected', 'OAuth Connected'), ('oauth_disconnected', 'OAuth Disconnected'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_verified', 'MFA Verified'), ('mfa_failed', 'MFA Failed'), ('mfa_backup_used', 'MFA Backup Code Used'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('request_created', 'Request Created'), ('request_cancelled', 'Request Cancelled'), ('token_generated', 'Token Generated'), ('token_accessed', 'Token Accessed'), ('token_expired', 'Token Expired'), ('token_invalid_attempt', 'Token Invalid Attempt'), ('print_initiated', 'Print Initiated'), ('print_completed', 'Print Completed'), ('print_failed', 'Print Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('request_received', 'Print Request Received'), ('request_sent', 'Print Request Sent'), ('printing', 'Document Being Printed'), ('printed', 'Document Printed'), ('expired', 'Request Expired'), ('cancelled', 'Request Cancelled'), ('document_deleted', 'Document Deleted'), ('print_failed', 'Print Failed')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='oauthconnection',
            unique_together={('user', 'provider')},
        ),
    ]
